version: '3'
services:
    build:
        image: ptfseurope/koha-debs:${KDD_IMAGE}
        privileged: true
        volumes:
            - ${SYNC_REPO}:/kohaclone
            - ${DEBS_OUT}:/kohadebs
        env_file:
            - .env
