version: '3'
services:
    build:
        image: ghcr.io/openfifth/koha-dpkg-docker:${KDD_IMAGE}
        privileged: true
        volumes:
            - ${SYNC_REPO}:/kohaclone
            - ${DEBS_OUT}:/kohadebs
        env_file:
            - .env
