version: '3'
services:
    koha-debs:
        image: ptfseurope/koha-debs:${BUILD_IMAGE}
        privileged: true
        volumes:
            - ${SYNC_REPO}:/kohaclone
            - ${DEBS_OUT}:/kohadebs
        env_file:
            - .env
